// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvE2NO0l_KZIrBwr3zj8hTC1n31ZobB8',
    appId: '1:606446741951:web:3647b9fe8f8c9af0e9990a',
    messagingSenderId: '606446741951',
    projectId: 'passwordup',
    authDomain: 'passwordup.firebaseapp.com',
    storageBucket: 'passwordup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFau9tmrUzgRYkaW1NWqtK3-oL8vrzROE',
    appId: '1:606446741951:android:640fe9ed2a8b48bce9990a',
    messagingSenderId: '606446741951',
    projectId: 'passwordup',
    storageBucket: 'passwordup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ZhdhPSqZRqFjpZiI48mY_XfTdbfuA-c',
    appId: '1:606446741951:ios:8069580ce787f97ee9990a',
    messagingSenderId: '606446741951',
    projectId: 'passwordup',
    storageBucket: 'passwordup.appspot.com',
    iosBundleId: 'com.example.passwordup',
  );
}
